Repository Financial-Times/dotcom-page-kit, pull requests merged in 2020-04, with the labels that each got.

#785 Remove `role="contentinfo"` from `o-footer` markup.
  packages/dotcom-ui-footer/src/components/partials.tsx
Labels: UI

#786 Updating version of o-fonts-assets
  packages/dotcom-ui-base-styles/src/lib/fontFaces.ts
  packages/dotcom-ui-base-styles/styles.scss
  packages/dotcom-ui-shell/src/__test__/components/__snapshots__/Shell.test.tsx.snap
Labels: Housekeeping, UI

#788 fix dotcom-build-base package name
  packages/dotcom-build-base/package.json
Labels: Build tools, Housekeeping

#789 update CODEOWNERS to @financial-times/platforms team
  CODEOWNERS
Labels: Housekeeping

#793 Remove tests which expect the length of a function
  packages/dotcom-middleware-app-context/src/__test__/index.spec.ts
  packages/dotcom-middleware-asset-loader/src/__test__/index.spec.ts
Labels: Testing

#791 NOPS-71: Hide subscribe sticky nav button when screen is small
  packages/dotcom-ui-header/bower.json
  packages/dotcom-ui-header/src/components/navigation/partials.tsx
Labels: Bug, Refactor, UI

#797 Add v0.7.1 to changelog.md
  changelog.md
Labels: Documentation, Housekeeping
