Repository Financial-Times/dotcom-page-kit, pull requests merged in 2020-02, with the labels that each got.

#745 feat: allow passing in of getCurrentPath option
  examples/ft-ui/__test__/logged-in-user.test.js
  package.json
  packages/dotcom-middleware-navigation/readme.md
  packages/dotcom-middleware-navigation/src/__test__/navigation.spec.ts
  packages/dotcom-middleware-navigation/src/navigation.ts
  packages/dotcom-ui-header/src/index.tsx
  packages/dotcom-ui-layout/src/components/Layout.tsx
  scripts/generate-storybook-config.js
Labels: Enhancement, Server-side integration

#749 change lint-staged rules to only format staged files
  package.json
Labels: Housekeeping

#750 Use SVG header for TopColumnCenterNoLink
  packages/dotcom-ui-header/src/components/top/partials.tsx
Labels: Refactor, UI

#751 Correct background-color for combined-hbs-jsx example
  examples/combined-hbs-jsx/views/Home.jsx
  examples/combined-hbs-jsx/views/home.hbs
Labels: Bug, Example app

#753 Enable MainHeader logo link to be switched off
  packages/dotcom-ui-header/README.md
  packages/dotcom-ui-header/src/__stories__/story.tsx
  packages/dotcom-ui-header/src/index.tsx
Labels: Enhancement, UI

#747 Uppercase README filenames
  .storybook/README.md
  README.md
  architecture.md
  docs/design-decisions/code-splitting-strategy.md
  docs/guides/extending-webpack-and-babel.md
  examples/README.md
  examples/building-sass-files/README.md
  examples/combined-hbs-jsx/README.md
  examples/dynamic-imports/README.md
  examples/express-with-handlebars/README.md
  examples/express-with-jsx/README.md
  examples/ft-ui/README.md
  packages/dotcom-build-bower-resolve/README.md
  packages/dotcom-build-sass/README.md
  packages/dotcom-middleware-app-context/README.md
  packages/dotcom-middleware-asset-loader/README.md
  packages/dotcom-middleware-navigation/README.md
  packages/dotcom-page-kit-pluggable/README.md
  packages/dotcom-server-app-context/README.md
  packages/dotcom-server-asset-loader/README.md
  packages/dotcom-server-handlebars/README.md
  packages/dotcom-server-handlebars/src/helpers/README.md
  packages/dotcom-server-navigation/README.md
  packages/dotcom-server-react-jsx/README.md
  packages/dotcom-ui-app-context/README.md
  packages/dotcom-ui-bootstrap/README.md
  packages/dotcom-ui-flags/README.md
  packages/dotcom-ui-footer/README.md
  packages/dotcom-ui-header/README.md
  packages/dotcom-ui-layout/README.md
  packages/dotcom-ui-polyfill-service/README.md
  packages/dotcom-ui-shell/README.md
Labels: Documentation, Housekeeping

#762 Add comment which lists all items in the default set
  packages/dotcom-ui-polyfill-service/src/polyfillServiceURLs.ts
Labels: Documentation

#764 Use Dart Sass for Sass implementation
  packages/dotcom-build-sass/README.md
  packages/dotcom-build-sass/package.json
  packages/dotcom-build-sass/src/plugin.ts
Labels: Build Plugin

#768 Update dotcom-ui-layout README description
  packages/dotcom-ui-layout/README.md
Labels: Bug, Documentation

#773 add missing react dependency to dotcom-server-handlebars
  packages/dotcom-server-handlebars/package.json
Labels: Bug, Server-side integration
